apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: chatapp
  template:
    metadata:
      labels:
        app: chatapp
    spec:
      containers:
      - name: chatapp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
