apiVersion: v1
kind: Service
metadata:
  name: chatapp-frontend-svc
spec:
  selector:
    app: chatapp-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: chatapp-backend
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
