replicaCount: 1

backend:
  image:
    repository: 182138815046.dkr.ecr.ap-south-1.amazonaws.com/chatapp-backend
    tag: latest

frontend:
  image:
    repository: 182138815046.dkr.ecr.ap-south-1.amazonaws.com/chatapp-frontend
    tag: latest

service:
  type: LoadBalancer
  port: 80
