pipeline {
    agent any

    parameters {
        string(name: 'IMAGE_TAG',  defaultValue: 'latest',  description: 'Docker image tag')
        choice(name: 'TARGET_ENV', choices: ['dev', 'staging', 'prod'], description: 'Target environment')
    }

    environment {
        AWS_REGION       = 'ap-south-1'
        ECR_REGISTRY     = '182138815046.dkr.ecr.ap-south-1.amazonaws.com'
        EKS_CLUSTER_NAME = 'chatapp-cluster'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-token',
                    url: 'https://github.com/Kishorgavhane/chatapp.git'
                echo "✅ Code checkout complete"
            }
        }

        stage('Configure AWS + kubectl') {
            steps {
                withCredentials([aws(credentialsId: 'aws-credentials')]) {
                    sh '''
                        aws eks update-kubeconfig \
                            --name $EKS_CLUSTER_NAME \
                            --region $AWS_REGION
                        kubectl get nodes
                    '''
                }
                echo "✅ kubectl configured"
            }
        }

        stage('ECR Login') {
            steps {
                withCredentials([aws(credentialsId: 'aws-credentials')]) {
                    sh '''
                        aws ecr get-login-password --region $AWS_REGION | \
                        docker login --username AWS \
                        --password-stdin $ECR_REGISTRY
                    '''
                }
                echo "✅ ECR Login successful"
            }
        }

        stage('Deploy') {
            steps {
                withCredentials([aws(credentialsId: 'aws-credentials')]) {
                    sh '''
                        kubectl get namespace ${TARGET_ENV} || \
                        kubectl create namespace ${TARGET_ENV}
                        kubectl get pods -n ${TARGET_ENV} || true
                        echo "✅ Deployed to ${TARGET_ENV}"
                    '''
                }
            }
        }

        stage('Production Approval') {
            when {
                expression { params.TARGET_ENV == 'prod' }
            }
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    input message: '🚀 Production deploy confirm?',
                          ok: 'Deploy!'
                }
            }
        }

    }

    post {
        success {
            echo "🎉 ${params.TARGET_ENV} deployment successful!"
        }
        failure {
            echo "❌ Deployment failed! Check logs."
        }
        always {
            cleanWs()
        }
    }
}
